- name: "[nginx] install curl"
  ansible.builtin.apt:
    name: curl
    state: latest

- name: "[nginx] install gnupg2"
  ansible.builtin.apt:
    name: gnupg2
    state: latest

- name: "[nginx] install ca-certificates"
  ansible.builtin.apt:
    name: ca-certificates
    state: latest

- name: "[nginx] install lsb-release"
  ansible.builtin.apt:
    name: lsb-release
    state: latest

- name: "[nginx] install ubuntu-keyring"
  ansible.builtin.apt:
    name: ubuntu-keyring
    state: latest

- name: "[nginx] install apt source"
  block:
    - name: get key
      ansible.builtin.get_url:
        url: https://nginx.org/keys/nginx_signing.key
        dest: /usr/share/keyrings/nginx-archive-keyring.asc
        mode: '0644'
        force: true

    - name: add apt source
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.asc] http://nginx.org/packages/ubuntu {{ ansible_distribution_release }} nginx"

- name: "[nginx] install nginx"
  ansible.builtin.apt:
    name: nginx
    state: latest
    update_cache: true

- name: "[nginx] get Mozilla dhparam"
  ansible.builtin.get_url:
    url: https://ssl-config.mozilla.org/ffdhe2048.txt
    dest: /etc/nginx/dhparam

- name: "[nginx] install main configuration"
  template:
    src: templates/nginx-conf.j2
    dest: /etc/nginx/nginx.conf
