- name: "{{ item.key }}: create ssl config"
  template:
    src: templates/site-ssl-config.j2
    dest: /etc/nginx/sites-ssl-available/{{ item.key }}
  vars:
    domain: "{{ item.key }}"
    www_domain: "{{ item.value.www_domain | default(false) }}"
    redirect_domain: "{{ item.value.redirect_domain | default(false) }}"
