---
- hosts: web
  become: true
  remote_user: airborne
  vars:
    sites:
      aaronbieber.com:
        www_domain: www.aaronbieber.com
      blog.aaronbieber.com:
      deck.aaronbieber.com:
      status.aaronbieber.com:
      aaronbieber.art:
      beta.aaronbieber.coach:
      blog.aaronbieber.coach:
        redirect_domain: "thecuriousleader.work"
      thecuriousleader.work:
      nathanbieber.com:
      singleservingphoto.com:
        www_domain: www.singleservingphoto.com
      bitdepth.show:

  tasks:
    - name: ensure latest nginx is installed
      apt: name=nginx state=latest

    - name: ensure apache2 is not installed
      apt: name=apache2 state=absent

    - name: ensure nginx starts at boot
      service: name=nginx enabled=yes

    - name: stop nginx
      service: name=nginx state=stopped

    - name: ensure snapd is up to date
      command: snap install core && snap refresh core

    - name: ensure certbot snap is installed
      command: snap install --classic certbot

    - name: make certbot available
      file:
        src: /snap/bin/certbot
        path: /usr/bin/certbot
        state: link

    - name: create all sites root
      file:
        path: /var/www
        state: directory
        owner: www-data
        group: www-data
        mode: "u=rwx,g=rwx,o=rX,g+s"

    - include: site_root.yml
      with_dict: "{{ sites }}"

    - include: site_config.yml
      with_dict: "{{ sites }}"

    - name: start nginx
      service: name=nginx state=started

    - include: site_ssl.yml
      with_dict: "{{ sites }}"
