---
- hosts: web
  become: true
  remote_user: airborne
  vars:
    sites:
      aaronbieber.com:
        www_domain: www.aaronbieber.com
      blog.aaronbieber.com:
      deck.aaronbieber.com:
      status.aaronbieber.com:
      aaronbieber.art:
      aaronbieber.coach:
      blog.aaronbieber.coach:
        redirect_domain: "thecuriousleader.work"
      thecuriousleader.work:
      nathanbieber.com:
      singleservingphoto.com:
        www_domain: www.singleservingphoto.com
      bitdepth.show:
      therebelweb.org:

  tasks:
    - include_tasks: nginx_setup.yml

    - name: ensure apache2 is not installed
      apt: name=apache2 state=absent

    - name: ensure nginx starts at boot
      service: name=nginx enabled=yes

    - name: start nginx
      service: name=nginx state=started

    - name: ensure snapd core is installed
      command: snap install core

    - name: ensure snapd is updated
      command: snap refresh core

    - name: ensure certbot snap is installed
      command: snap install --classic certbot

    - name: make certbot available
      file:
        src: /snap/bin/certbot
        path: /usr/bin/certbot
        state: link

    - name: create all sites root
      file:
        path: /var/www
        state: directory
        owner: www-data
        group: www-data
        mode: "u=rwx,g=rwx,o=rX,g+s"

    - name: create ssl config dir
      file:
        path: /etc/nginx/sites-ssl-available
        state: directory
        owner: root
        group: root
        mode: "u=rwx,g=rx,o=rx"

    - name: remove ssl configs enabled dir
      file:
        path: /etc/nginx/sites-ssl-enabled
        state: absent

    - name: (re-)create ssl configs enabled dir
      file:
        path: /etc/nginx/sites-ssl-enabled
        state: directory
        owner: root
        group: root
        mode: "u=rwx,g=rx,o=rx"

    - include_tasks: site_root.yml
      with_dict: "{{ sites }}"

    - include_tasks: site_config.yml
      with_dict: "{{ sites }}"

    - include_tasks: site_ssl_config.yml
      with_dict: "{{ sites }}"

    - name: restart nginx
      service: name=nginx state=restarted

    - include_tasks: site_ssl_cert_request.yml
      with_dict: "{{ sites }}"

    - include_tasks: site_ssl_config_enable.yml
      with_dict: "{{ sites }}"

    - name: restart nginx
      service: name=nginx state=restarted
